### PR TITLE
Saleh first commit

### PR DESCRIPTION
**Pull request by SalehMammadov**
I finished my codes

### CODE REVIEW

**Comment by ElenaChekirka** [comment]
Looks perfect

**Review by ElenaChekirka — APPROVED** [review]
Looks perfect

**Review by nihalyorulmaz — CHANGES_REQUESTED** [review]
change your sentence :)

**Review by ElenaChekirka — APPROVED** [review]
I like it

**Review by nihalyorulmaz — APPROVED** [review]
now looks great!

**Pull request merged**
